# Generated by Django 5.0.4 on 2024-04-14 11:06

import call.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=13, validators=[call.models.validate_uzbek_phone_number])),
                ('companyName', models.CharField(max_length=200, unique=True)),
                ('twilioToken', models.CharField(max_length=400)),
                ('twilioSid', models.CharField(max_length=400)),
                ('twilioNumber', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=13, validators=[call.models.validate_uzbek_phone_number])),
                ('info', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.company')),
            ],
        ),
    ]
